### ISSUE TITLE
[Question]injector whether support GenericType like “List<String>”?

### ISSUE THREAD

**Issue by Guang1234567** [tikkrapp/injector#12]
Hello dev:

injector whether support GenericType like “`SomeGenericType<String>`”?

```dart
injector.registerDependency <SomeGenericType<String>>((i) => new SomeGenericType("Hello"));
```

thanks.

**Comment by JulianBissekkou** [comment]
Hello, 

I am not sure if I understood the question correctly. 
However, you are able to register dependencies with a generic type.

so of course `injector.registerDependency<List<String>>(...)` works **as long as you are requesting the dependency with the exact same type**. `injector.getDependency<List<String>>();`.

another example would be something like this: 
`
injector.registerDependency<Iterable<String>>((_) => <String>["Clear", "now?"]);
`
or

`
_injector.registerDependency<Repository<User>>((_) => MemoryRepository<User>());
`

**Comment by Guang1234567** [comment]
@JulianBissekkou 

Thanks your reply. ^_^

I also have another question like below:

> I register two `Car` by the injector,  but how to` getDependency<Car>` them separately?

```dart
// the first  car instance
injector.registerDependency<Car>((injector) {
      var engine = injector.getDependency<Engine>();
      var fuel = injector.getDependency<Fuel>();
      var driver = injector.getDependency<Driver>();
      
      return CarImpl_01(engine,fuel,driver);
    });
    
//  the second car instance
 injector.registerDependency<Car>((injector) {
          var engine = injector.getDependency<Engine>();
          var fuel = injector.getDependency<Fuel>();
          var driver = injector.getDependency<Driver>();
          
          return CarImpl_02(engine,fuel,driver);
        });

```

**Comment by JulianBissekkou** [comment]
Currently, this is not possible and I wonder what use case you have for that 🤔 ? 

However, I thought about implementing some kind of "Tag-Feature". 
You could register a dependency on a specific tag. This could look something like this: 

`
injector.registerDependency<Car>("gasoline",(injector) {
      var engine = injector.getDependency<Engine>();
      var fuel = injector.getDependency<Fuel>();
      var driver = injector.getDependency<Driver>();
      
      return GasolineCar(engine,fuel,driver);
    });
    
 injector.registerDependency<Car>("electric",(injector) {
          var engine = injector.getDependency<ElectricEngine>();
          var driver = injector.getDependency<Driver>();
          
          return ElectricCar(engine,driver);
        });`

Would this be helpful? Let me know! 👍

**Comment by Guang1234567** [comment]
“Tag-Feature”  is very useful for product variants. (https://developer.android.com/studio/build/build-variants <https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwi1lbztn8rfAhUTY48KHbWwB04QFjABegQIBBAB&url=https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Fbuild%2Fbuild-variants%3Fhl%3Dzh-cn&usg=AOvVaw1k7raX08Sen0oBuU2Xa7yX>).

For example:

In  free version, we provide GasolineCar;
In paid version, we provide ElectricCar.


thanks.

**Comment by Guang1234567** [comment]
In addition,  i thought about `Injector` maybe not singleton like below:

https://github.com/tikkrapp/injector/blob/40d2acae24037dc32e30b07561ab4a4b5d58be9c/lib/src/injector_base.dart#L13-L24

Because i used to use `goolge/dagger2` in android before dart.
Sometimes our App lifecycle may spilt into three scope like `AppScope`, `UseScope` and `ActivityScope` that corresponding to the `AppScopeInjector`, `UserScopeInjector` and `ActivityInjector`.

For example:

class Car {
  final Energy _energy;

 Car(this._energy);
}


`UserScopeInjector`  will be disposed when the login user was changed.
And `UserScopeInjector` maybe depends on `AppScopeInjector` like below:

```dart

appScopeInjector.registerDependency<Energy>("gasoline", (injector) {
      return Gasoline();
    });

userScopeInjector.registerDependency<Car>((injector) {
      return Car(appScopeInjector.getDependency<gasoline>(););
    });


```

**Comment by JulianBissekkou** [comment]
Here is the issue for the scope feature.
Add your ideas or feature requests if you want! 👍 
I will start the draft tomorrow and keep you updated. Any other questions or feature ideas?
