### ISSUE TITLE
Feature: Custom scopes

### ISSUE THREAD

**Issue by JulianBissekkou** [tikkrapp/injector#13]
Instead of just using singletons or providers for dependencies, the injector should be able to support different scopes similar to dagger2 scopes.

We will work on a draft on how the api could look like. 🔨 
Ideas and feedback are wanted! 👍

**Comment by stefanschaller** [comment]
@Guang1234567 We removed the forced singleton! 
You can create different instances of the injector. 

We will add scopes in the future. But we don't have currently enough time to do it! Thank you :)
