### ISSUE TITLE
Named definitions

### ISSUE THREAD

**Issue by AlexeyPoldeo** [tikkrapp/injector#14]
It will be great to add optional name parameter on registering and getting an object

**Comment by JulianBissekkou** [comment]
so you are able to get the dependency with that name later on?

**Comment by AlexeyPoldeo** [comment]
Yes. Sometimes it's required to inject objects of same class, but different purposes.
Like username and password - both are String.

**Comment by stefanschaller** [comment]
In version 1.0.5 we added support for named dependencies

**Comment by AlexeyPoldeo** [comment]
But this is not reflected in Readme...
