### ISSUE TITLE
Parameters in getDependency function

### ISSUE THREAD

**Issue by RomanKapshuk** [tikkrapp/injector#19]
Can you provide additional parameter in the getDependency function of Injector?

Example of use

`Injector.appInstance.registerDependency<ImportantInterface>((injector, params) => ImportantImplementation(params['someDetailsId']));`

`Injector.appInstance.getDependency<ImportantInterface>(MapEntry('someDetailsId', 1));`

**Comment by JulianBissekkou** [comment]
We thought about this in the past and decided to not implement this since a `Map` or a `MapEntry` is less typesafe. A more typesafe option would be a Factory Method. Here is an example.

```dart
// this is now more typesafe especially for more arguments 
// or if you pass an object into your factory since you don't have to cast
typedef ImportantInterface ImportantFactory(int id);

Injector.appInstance.registerDependency<ImportantFactory>((injector) {
    return (id) => ImportantImplementation(id);
});


final factory = Injector.appInstance.getDependency<ImportantFactory>();
final importantInstance = factory(1); //1 is someDetailsId
```

If you feel like this is a little too complicated we could work on an api that is still typesafe and easier to use. Let me know what you think :)

**Comment by JulianBissekkou** [comment]
@RomanKapshuk Feedback would be appreciated 👍

**Comment by RomanKapshuk** [comment]
@JulianBissekkou Thanks for almost immediately answer :)

I think it is not obvious for Di library. Because I expect that interface of library will provide me exactly the instance of dependency, but not a factory.

But now it's fine solution, thanks!

**Comment by JulianBissekkou** [comment]
Okay great, I will close this now. If you have any other questions you can always create a new issue :).
