### ISSUE TITLE
Injector Exception: Cannot find object factory

### ISSUE THREAD

**Issue by tony123S** [tikkrapp/injector#20]
I'm using Injection and AnimationController in my Flutter project

```
 injector.map<Provider>((_) => 
 ProviderImpl(injector.get<AnimationController>()),
      isSingleton: true);
```
**ProviderImpl**

`ProviderImpl(AnimationController _controller) : super();`

But getting this issue

```
I/flutter (17236): Injector Exception: Cannot find object factory for 'AnimationController::default'
I/flutter (17236):
```

**Comment by bedel-lemotio** [comment]
I have a same problems

**Comment by JulianBissekkou** [comment]
@bedel-lemotio 
I didn't answer to this issue since it was closed immediately. 
Can you provide more information on how you register and get the dependency?

**Comment by bedel-lemotio** [comment]
I'm using flutter_simple_dependency_injection  my Flutter project


`import` 'package:beneficiary/core/states/app_state.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:flutter_simple_dependency_injection/injector.dart' as prefix1;
import 'package:states_rebuilder/states_rebuilder.dart';

class ServiceProviderViewModel extends StatesRebuilder {

  bool loading =false;
  List<ServiceProvider> _serviceProviderlist;
  List<ServiceProvider> get serviceProviders => _serviceProviderlist;

  ServiceProvider _serviceProvider;
  ServiceProvider get serviceProvider => _serviceProvider;

  var api = prefix1.Injector.getInjector().get<Test>();
  var analytics = prefix1.Injector.getInjector().get<FirebaseAnalytics>();
  
  Future getServiceProviders(String connid,String cl,String cc,String cityId,String l1,String l2) async{
    if(_serviceProviderlist == null){
      loading = true;

      //_serviceProviderlist = await prefix1.Injector.getInjector().get<ApiService>().getServiceProviders(connid, cl, cc, cityId, l1, l2);
    loading =false;
      rebuildStates([AppState.serviceProviderList]);
    }
  }
}`
My class test

class Test {
  static const String BASEURL = "https://iziway.cm/api";
  //static const String BASEURL = "https://gtastore.azurewebsites.net/api";
  //static const String BASEURL = "http://192.168.43.22:55390/api";
  Dio http;



  Future<List<Prescription>> getWishList() async {
    var response = await http.get('/shoppingCart/wishlist');
    if (response.data['StatusCode'] != 200) {
      throw ApiErrorException((response.data['ErrorList'] as List).join(", "));
    }
    return (response.data['Items'] as List).map((el) => Prescription.fromJson(el)).toList();
  }

  }

But getting this issue
I/flutter ( 6408): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6408): The following InjectorException was thrown building Builder:
I/flutter ( 6408): Injector Exception: Cannot find object factory for 'Test::default'
I/flutter ( 6408): User-created ancestor of the error-causing widget was:
I/flutter ( 6408):   MaterialApp file:///C:/laragon/www/FLUTTER/PROJETS/beneficiary/lib/main.dart:46:12
I/flutter ( 6408): When the exception was thrown, this was the stack:
I/flutter ( 6408): #0      Injector.get (package:flutter_simple_dependency_injection/src/injector.dart:155:7)
I/flutter ( 6408): #1      new ServiceProviderViewModel (package:beneficiary/core/view_models/serviceprovider_viewmodel.dart:22:44)
I/flutter ( 6408): #2      _OrderListPageState.initState (package:beneficiary/ui/pages/serviceproviders/sp_list_page/sp_list_page.dart:19:33)

**Comment by JulianBissekkou** [comment]
You are using a different package and not the injector from this repository. 

I am not sure, but the problem is the missing type parameter in this line:

```dart
// Dart will infer this type as "dyamic"
var api = prefix1.Injector.getInjector().get();

// this should work
var api = prefix1.Injector.getInjector().get<YourApiType>();
```

If you don't want to run into similar issues in the future, feel free to use our injector package because we catch this error with an assertion 😉 

Besides that, it makes sense to disable `implicit-dynamic` in the analyzer options.
Keep in mind that this may require a little refactoring in your code base.
```yml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

**Comment by bedel-lemotio** [comment]
oui jai fais comme ca s-il vous plait regardez bien ma classe ServiceProviderViewModel 
class ServiceProviderViewModel extends StatesRebuilder {

  bool loading =false;
  List<ServiceProvider> _serviceProviderlist;
  List<ServiceProvider> get serviceProviders => _serviceProviderlist;

  ServiceProvider _serviceProvider;
  ServiceProvider get serviceProvider => _serviceProvider;

  ApiService api = prefix1.Injector.getInjector().get<ApiService>();

  var analytics = prefix1.Injector.getInjector().get<FirebaseAnalytics>();

  Future getServiceProviders(String connid,String cl,String cc,String cityId,String l1,String l2) async{
    if(_serviceProviderlist == null){
      loading = true;
      _serviceProviderlist = api.getServiceProviders(connid, cl, cc, cityId, l1, l2) as List<ServiceProvider>;
      //_serviceProviderlist = await prefix1.Injector.getInjector().get<ApiService>().getServiceProviders(connid, cl, cc, cityId, l1, l2);
    loading =false;
      rebuildStates([AppState.serviceProviderList]);

    }
    
  }
}

**Comment by JulianBissekkou** [comment]
Where do you register the instance of `ApiService ` or `FirebaseAnalytics `?

**Comment by bedel-lemotio** [comment]
that's API services

```
class ApiService {
  static const String BASE = "https://api.test.com";
  final  BASE_URL = "${BASE}/ghi/c/b/";
  Dio http;

  void init() async {
    var headers = <String, dynamic>{
      "Content-Type": "application/json",
      "Accept": "application/json",
    };
    http = Dio(BaseOptions(baseUrl: BASE_URL, headers: headers));
  }

  /**
   * Execute a GET request for fetching a serviceproviders
   **/
  Future<List<ServiceProvider>> getServiceProviders(
      String connid,
      String cl,
      String cc,
      String cityId,
      String l1,
      String l2,
      ) async {
    var response = await http.get('?op=qsps',queryParameters: {
      "connid": connid,
      "c1": cl,
      "cc": cc,
      "cityId": cityId,
      "l1": l1,
      "l2": l2
    });
    if (response.data['StatusCode'] != 200) {
      throw ApiErrorException((response.data['ErrorList'] as List).join(", "));
    }
    return (response.data['Data'] as List).map((el) => ServiceProvider.fromJson(el)).toList();
  }
```

**Comment by JulianBissekkou** [comment]
You have to register the instance somwhere.
This injector uses `registerDependency`  for that.


According to the readme, you have to call `map` and initialize your injector.
https://github.com/jonsamwell/flutter_simple_dependency_injection

Please open an issue at the correct repository if this does not fix the issue.
