### ISSUE TITLE
Is a service locator, really?

### ISSUE THREAD

**Issue by paul-hammant** [tikkrapp/injector#21]
So remembering that DI containers do not support global mutable state, is it the case that your technology Injector is really a "Service Locator". Albeit one backed by a DI container (implemented as a map)?

**Comment by JulianBissekkou** [comment]
Since Injector is using a map internally I would agree that you could also name it Service Locator.
If you are looking for "a real DI" you can check out https://github.com/google/inject.dart .

**Comment by paul-hammant** [comment]
I've see it and other other DI solutions for Dart - I'm cataloging all DI/IoC solutions in all languages presently - thanks for replying :)

**Comment by devzsolt** [comment]
@paul-hammant could you please share your Dart DI catalog?
