### ISSUE TITLE
Wrong registration order

### ISSUE THREAD

**Issue by westito** [tikkrapp/injector#40]
I get wrong registration order when using "env" modifier.
I have two implementation of the same interface as Singleton. The two implementation have different env provided. In the generated injector the first implementation registered before all usages, but the other implementation registered later in the file. So it is working in one env, but fails in the other ( Object/factory with type Repository is not registered inside GetIt.)

```
abstract interface class Repository {
}

@Singleton(as: Repository, env: [AppEnvironment.demo])
class RepositoryDemo implements Repository {
}

@Singleton(as: Repository, env: [AppEnvironment.dev, AppEnvironment.uat])
class RepositoryDev implementsRepository {
}
```

**Comment by JulianBissekkou** [comment]
I think you opened this issue in the wrong repository since this injector package does not support any kind of annotations.

**Comment by westito** [comment]
Yeah sorry, simmilar name, other package!
